apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: "{{ .Values.nginx.namespace }}"
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image }}"
        volumeMounts:
          name: domain-scan-pvc
          mountPath: /usr/share/nginx/html
          readOnly: true
        env:
        - name: NGINX_PORT
          value: 80
        ports:
        - containerPort: 80
          name: http
