apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: "{{ .Values.nginx.namespace }}"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: domain-scan-pvc
          persistentVolumeClaim:
            claimName: "{{ .Values.pvc.name }}"
        - name: default
          configMap:
            name: nginx-config-map
            items:
            - key: default
              path: default.conf 
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: domain-scan-pvc
            readOnly: true
          - mountPath: /etc/nginx/conf.d
            name: default
        ports:
        - containerPort: 80
          name: http
