apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: "{{ .Values.nginx.namespace }}"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: domain-scan-pvc
          persistentVolumeClaim:
            claimName: "{{ .Values.pvc.name }}"
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: domain-scan-pvc
            readOnly: true
        ports:
        - containerPort: 80
          name: http
        command: ["/bin/sh"]
        args: ["-c", "/bin/sed -i '/index.html /a autoindex on;' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
