kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.nginx.appName }}
  namespace: {{ .Values.nginx.namespace }}
spec:
  selector:
    app: {{ .Values.nginx.appName }}
  ports:
    - protocol: "TCP"
      name: http
      port: 80
      targetPort: "{{ .Values.nginx.port }}"
  type: ClusterIP
