apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.pvc.name }}"
  namespace: "{{ .Values.pvc.namespace }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: default
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:  
  - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.pvc.size }}"
